[env:lilygo-t-display-ttgo]
board = lilygo-t-display-ttgo
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-ttgo>
; ===== REMOVE WIFI ATTACKS =====
    -<src/modules/wifi/karma_attack.cpp>
	    -<src/modules/wifi/evil_portal.cpp>
		    -<src/modules/wifi/deauth.cpp>
			    -<src/modules/wifi/sniffer.cpp>
				    -<src/modules/wifi/responder.cpp>
					    -<src/modules/wifi/wardriving.cpp>
						    -<src/modules/wifi/wireguard.cpp>
							    -<src/modules/wifi/brucegotchi.cpp>
; ===== REMOVE RF =====
    -<src/modules/rf/>
	    -<src/modules/subghz/>

		    ; ===== REMOVE IR =====
			    -<src/modules/ir/>

				    ; ===== REMOVE FM =====
					    -<src/modules/fm/>

						    ; ===== REMOVE GPS =====
							    -<src/modules/gps/>

								    ; ===== REMOVE PWNAGOTCHI =====
									    -<src/modules/pwnagotchi/>

										    ; ===== REMOVE LORA =====
											    -<src/modules/lora/>

												    ; ===== REMOVE ETHERNET =====
													    -<src/modules/ethernet/>

														    ; ===== REMOVE AUDIO =====
															    -<src/modules/audio/>

																    ; ===== REMOVE NRF =====
																	    -<src/modules/nrf/>

																		    ; ===== REMOVE USB =====
																			    -<src/modules/usb/>

																				    ; ===== REMOVE UNUSED SERIAL COMMANDS =====
																					    -<src/core/serial_commands/rf_commands.cpp>
																						    -<src/core/serial_commands/ir_commands.cpp>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/lilygo-t-display-ttgo
	-DREDRAW_DELAY=1 # Used to improve navigation on menus for this device

	-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;-UARDUINO_USB_CDC_ON_BOOT #Turn off CDC on boot https://github.com/Xinyuan-LilyGO/T-Display-S3
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DDEVICE_NAME='"Lilygo T-Display TTGO"'

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button

lib_ignore =
	${env_4mb.lib_ignore}
